### ISSUE TITLE
decrease python version requirement

### ISSUE THREAD

**Issue by yves-renier** [RamtinYazdanian/fasttext-reducer#1]
Hello,
the package only requires fasttext-wheel which is compatible with python>=3.4., however in fasttext-reducer's pyproject.toml, python>=3.11 is required.
I aslo tested fasttext-reducer without issue on python 3.8.
Could the requirement in pyproject.toml be relaxed to allow for older python version ?

**Comment by RamtinYazdanian** [comment]
Solved in v0.1.2 by reducing requirement to Python 3.8
